github: [fabiocaccamo]
polar: fabiocaccamo
ko_fi: fabiocaccamo
liberapay: fabiocaccamo
tidelift: pypi/python-fontbro
custom: ["https://www.buymeacoffee.com/fabiocaccamo", "https://www.paypal.me/fabiocaccamo"]
