name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # run once a month

jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-data.txt
          pip install -r requirements-test.txt

      - name: Update data
        run: |
          python scripts/update_data.py

      - name: Run pre-commit
        continue-on-error: true
        run: |
          pre-commit run --files fontbro/data/unicode-blocks.json fontbro/data/unicode-scripts.json

      - name: Commit data
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            fontbro/data/unicode-blocks.json
            fontbro/data/unicode-scripts.json
          commit-msg: "Update `unicode-blocks.json` and `unicode-scripts.json` data."
          committer-name: "Fabio Caccamo [bot]"
          committer-email: "fabio.caccamo@gmail.com"
          github-token: ${{ secrets.WORKFLOWS_UPDATE_DATA_TOKEN }}
